### ISSUE TITLE
A bit elaborate readme

### ISSUE THREAD

**Issue by dy** [WebReflection/dom-augmentor#10]
Hi @WebReflection!

That is really useful module, thank you for your work indeed. I believe it can provide a solid base for  other frameworks.

Is there any chance I can request elaborate readme a bit? A bit more practically detailed case would be of great help.

**Comment by WebReflection** [comment]
Unfortunately I have no time to maintain this project, since I don't use it much myself.

I have hence updated the README with the current status:
https://github.com/WebReflection/dom-augmentor#dom-augmentor

Apologies for any inconvenience.
