### ISSUE TITLE
Two effects at once not working?

### ISSUE THREAD

**Issue by SirPepe** [WebReflection/dom-augmentor#20]
This may not be a bug but rather my lack of experience with hooks, but [I would expect the following to work with dom-augmentor](https://codepen.io/SirPepe/pen/wvBKjvO?editors=1011) ([it does work with React](https://stackblitz.com/edit/two-effect-hooks?file=index.js)):

```javascript

// Some hook that sets state when some external callback fires
const usePlus = () => {
  const [ state, setState ] = useState(0);
  const result = useRef(state);
  useEffect( () => {
    console.log("plus effect");
    const handler = () => setState(++result.current);
    document.querySelector(".plus").addEventListener("click", handler);
    return () => {
      console.log("plus cleanup");
      document.querySelector(".plus").removeEventListener("click", handler);
    };
  }, []);
  return state;
};

// The same as usePlus() above
const useMinus = () => {
  const [ state, setState ] = useState(0); 
  const result = useRef(state);
  useEffect( () => {
    console.log("minus effect");
    const handler = () => setState(++result.current);
    document.querySelector(".minus").addEventListener("click", handler);
    return () => {
      console.log("minus cleanup");
      document.querySelector(".minus").removeEventListener("click", handler);
    };
  }, []);
  return state;
};

const Content = () => $(() => {
  const plus = usePlus();   // this has no effect at all
  const minus = useMinus(); // this works
  return html`
    <div>
      +${ plus } / -${ minus } (${ plus - minus })
    </div>
  `;
});

render(document.querySelector(".result"), Content());
```

The second hook always works while the first one never even registers the click event. Is this intentional? If so, how would I use multiple side effects in my `Content` component?

**Comment by WebReflection** [comment]
can you please try `useState(0, {async: true});` in both cases and tell me how it goes?

**Comment by SirPepe** [comment]
[Does not change anything.](https://codepen.io/SirPepe/pen/XWJmqVg?editors=1011)

**Comment by WebReflection** [comment]
It should just work now 👋

**Comment by SirPepe** [comment]
Works like a charm, thank you!

**Comment by WebReflection** [comment]
Thanks, and BTW, you are basically reproducing [neverland](https://github.com/WebReflection/neverland/#readme) by your own, maybe worth having a look there ;-)

**Comment by SirPepe** [comment]
Yeah, but then I'd have to wrangle with TypeScript definitons again, gonna procrastinate on this for now.
